# Generated by Django 5.0.2 on 2024-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_usuario', models.CharField(max_length=25, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=25)),
                ('horario_atencion', models.IntegerField(verbose_name='Horario de Atención')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Ultimo Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta activada')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Cuenta de administrador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
