# Generated by Django 5.0.2 on 2025-10-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='Cuenta de tutor'),
        ),
    ]
