# Generated by Django 5.0.2 on 2025-10-25 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_usuario_is_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Asignatura')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de la Asignatura')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Asignatura Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Ayudantia',
            fields=[
                ('id_ayudantia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Ayudantía')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('sala', models.CharField(max_length=50, verbose_name='Sala o Aula')),
                ('fecha', models.DateField(verbose_name='Fecha de la Ayudantía')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('duracion', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('cupos_totales', models.IntegerField(verbose_name='Cupos Totales')),
                ('cupos_disponibles', models.IntegerField(verbose_name='Cupos Disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ayudantía Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudantias', to='loginApp.asignatura')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudantias_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ayudantía',
                'verbose_name_plural': 'Ayudantías',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='activa', max_length=20, verbose_name='Estado')),
                ('ayudantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='loginApp.ayudantia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('estudiante', 'ayudantia')},
            },
        ),
    ]
