# Generated by Django 5.0.2 on 2025-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudantia',
            name='fecha_cursada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se Cursó'),
        ),
        migrations.AddField(
            model_name='ayudantia',
            name='is_cursada',
            field=models.BooleanField(default=False, verbose_name='Ayudantía Cursada'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='asistio',
            field=models.BooleanField(default=False, verbose_name='Asistió a la Ayudantía'),
        ),
    ]
