# Generated by Django 5.0.2 on 2025-11-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_ayudantia_fecha_cursada_ayudantia_is_cursada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sede')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sede Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
    ]
