# Generated by Django 5.0.2 on 2024-04-08 15:46

import django.contrib.postgres.fields
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=25, verbose_name='Nombre de la Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('nombre_sn', models.CharField(max_length=30, verbose_name='Nombre de ServiceNow')),
                ('casos_disponibles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, editable=False, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clientManager.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
