# Generated by Django 5.0.2 on 2025-11-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='tema',
            field=models.CharField(default='default', max_length=50, verbose_name='Tema del Tenant'),
        ),
        migrations.CreateModel(
            name='AdministradorGlobal',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Es Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='global_admin_set', related_query_name='global_admin', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='global_admin_set', related_query_name='global_admin', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Administrador Global',
                'verbose_name_plural': 'Administradores Globales',
                'db_table': 'administradores_globales',
            },
        ),
    ]
