"""
Django settings for portalAutoatencion project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from dotenv import load_dotenv

load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-w+*cbtuky&ghmcctne!wlo24-5+839qm$takon9w3a25^*@i)^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']

# CSRF trusted origins - necesario para que el panel global funcione correctamente
# En producción, se configura desde variables de entorno
csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
is_render = os.getenv('RENDER') is not None
# Detectar si estamos en producción (Render, Railway, etc.) por la presencia de DATABASE_URL o dominio onrender.com
is_production = bool(os.getenv('DATABASE_URL')) or 'onrender.com' in os.getenv('ALLOWED_HOSTS', '')

# Inicializar lista de orígenes confiables
CSRF_TRUSTED_ORIGINS = []

# Si hay variable de entorno, parsearla
if csrf_origins:
    # Limpiar espacios y filtrar wildcards (Django no soporta wildcards en CSRF_TRUSTED_ORIGINS)
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() 
        for origin in csrf_origins.split(',') 
        if origin.strip() and not origin.strip().endswith('*')
    ]

# Si estamos en producción (Render), asegurar que el dominio esté incluido
if is_render or is_production:
    # Intentar obtener el dominio desde variables de entorno o usar el por defecto
    render_domain = os.getenv('RENDER_EXTERNAL_URL') or 'https://studia-8dmp.onrender.com'
    if render_domain not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_domain)
    # Logging para debug
    import sys
    sys.stdout.write(f'[CSRF] Configurado para producción - Orígenes: {CSRF_TRUSTED_ORIGINS}\n')
    sys.stdout.write(f'[CSRF] is_render: {is_render}, is_production: {is_production}\n')
    sys.stdout.flush()

# Si no hay orígenes configurados y no estamos en producción, usar valores por defecto de desarrollo
if not CSRF_TRUSTED_ORIGINS and not is_production:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://public-admin-panel.localhost:8000',
        'http://duoc.localhost:8000',
        'http://dsa.localhost:8000',
        'http://inacap.localhost:8000',
        'http://Inacap.localhost:8000',  # Agregar otros tenants según sea necesario
    ]


# Application definition

AUTHENTICATION_BACKENDS = [
    'loginApp.backend.UsuarioBackend',
    'globalAdmin.backends.AdministradorGlobalBackend',
    'django.contrib.auth.backends.ModelBackend'
]


SHARED_APPS = [
    'django_tenants',
    'clientManager',
    'globalAdmin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
]

TENANT_APPS = [
    'loginApp',
    'solicitudesManager',
    'api_mobile',
]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir al principio
    'api_mobile.middleware.ApiMobileTenantMiddleware',  # Para identificar tenant en API móvil
    'globalAdmin.middleware.ForcePublicSchemaMiddleware',  # Debe ir ANTES de TenantMainMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',  # Debe ejecutarse ANTES de acceder a request.session
    'globalAdmin.middleware_tenant_param.TenantParamMiddleware',  # Detectar tenant desde parámetro (DESPUÉS de SessionMiddleware, ANTES de TenantMainMiddleware)
    'django_tenants.middleware.main.TenantMainMiddleware',
    'globalAdmin.middleware_public.PublicRootMiddleware',  # Capturar 404 en raíz cuando no hay tenant
    'globalAdmin.middleware.PublicSchemaMiddleware',
    'globalAdmin.middleware.TenantThemeMiddleware',
    'globalAdmin.middleware.PublicSchemaAuthMiddleware',  # ANTES de AuthenticationMiddleware, DESPUÉS de SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portalAutoatencion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,  # Desactivado para usar loaders personalizados
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'globalAdmin.template_loaders.TenantThemeLoader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

DEFAULT_FILE_STORAGE = "django_tenants.files.storage.TenantFileSystemStorage"

MULTITENANT_RELATIVE_MEDIA_ROOT = "archivos/%s"

WSGI_APPLICATION = 'portalAutoatencion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Configuración de base de datos
# Soporta tanto variables de entorno individuales como DATABASE_URL
# Intentar importar dj_database_url (solo necesario en producción)
try:
    import dj_database_url
    DJ_DATABASE_URL_AVAILABLE = True
except ImportError:
    DJ_DATABASE_URL_AVAILABLE = False

# Detectar si estamos en un proceso de build (solo collectstatic)
# Durante el build, las variables de entorno de la base de datos pueden no estar disponibles
# NOTA: No incluimos 'migrate' o 'migrate_schemas' porque necesitan conectarse a la BD
import sys
_is_build_process = 'collectstatic' in sys.argv

# Intentar usar DATABASE_URL primero (para Render, Railway, etc.)
database_url = os.getenv('DATABASE_URL')

# Logging para debug (solo en producción)
if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
    import sys
    sys.stdout.write(f'[DB CONFIG] _is_build_process: {_is_build_process}\n')
    sys.stdout.write(f'[DB CONFIG] DATABASE_URL presente: {bool(database_url)}\n')
    sys.stdout.write(f'[DB CONFIG] DJ_DATABASE_URL_AVAILABLE: {DJ_DATABASE_URL_AVAILABLE}\n')
    if database_url:
        # Mostrar solo los primeros y últimos caracteres por seguridad
        masked_url = database_url[:20] + '...' + database_url[-20:] if len(database_url) > 40 else '***'
        sys.stdout.write(f'[DB CONFIG] DATABASE_URL (masked): {masked_url}\n')
    sys.stdout.flush()

# Prioridad 1: Si es un proceso de build, usar configuración dummy
if _is_build_process:
    # Durante el build, usar una configuración de PostgreSQL dummy
    # django-tenants requiere PostgreSQL, pero no intentaremos conectarnos realmente
    # Usamos un host inválido para que falle rápido si intenta conectarse
    DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': 'build_dummy',
            'USER': 'build_dummy',
            'PASSWORD': 'build_dummy',
            'HOST': '127.0.0.1',
            'PORT': '5433',  # Puerto diferente para que falle rápido
            'OPTIONS': {
                'connect_timeout': 0.01,  # Timeout muy corto (10ms)
            },
            'CONN_MAX_AGE': 0,  # No mantener conexiones
        }
    }
    # Deshabilitar la conexión automática durante el build
    # Esto evita que django-tenants intente conectarse al importar modelos
    import django.db.backends.base.base as db_base
    original_ensure_connection = db_base.BaseDatabaseWrapper.ensure_connection
    def noop_ensure_connection(self):
        # No hacer nada durante el build
        pass
    db_base.BaseDatabaseWrapper.ensure_connection = noop_ensure_connection
# Prioridad 2: Si hay DATABASE_URL, usarla (producción)
elif database_url:
    # Intentar usar dj_database_url si está disponible
    if DJ_DATABASE_URL_AVAILABLE:
        if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
            import sys
            sys.stdout.write('[DB CONFIG] Usando dj_database_url para parsear DATABASE_URL\n')
            sys.stdout.flush()
        db_config = dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
        # Forzar el engine de django-tenants
        db_config['ENGINE'] = 'django_tenants.postgresql_backend'
        db_config.setdefault('OPTIONS', {})['client_encoding'] = 'utf8'
        DATABASES = {
            'default': db_config
        }
        if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
            import sys
            sys.stdout.write(f'[DB CONFIG] Configurado con dj_database_url - HOST: {db_config.get("HOST", "N/A")}\n')
            sys.stdout.flush()
    else:
        # Parsear DATABASE_URL manualmente si dj_database_url no está disponible
        # Formato: postgresql://user:password@host:port/database
        if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
            import sys
            sys.stdout.write('[DB CONFIG] Parseando DATABASE_URL manualmente\n')
            sys.stdout.flush()
        from urllib.parse import urlparse
        parsed = urlparse(database_url)
        db_host = parsed.hostname or 'localhost'
        db_port = parsed.port or '5432'
        db_name = parsed.path[1:] if parsed.path else 'postgres'  # Remover el / inicial
        DATABASES = {
            'default': {
                'ENGINE': 'django_tenants.postgresql_backend',
                'NAME': db_name,
                'USER': parsed.username or 'postgres',
                'PASSWORD': parsed.password or '',
                'HOST': db_host,
                'PORT': str(db_port),
                'OPTIONS': {
                    'client_encoding': 'utf8'
                }
            }
        }
        if os.getenv('RENDER') or os.getenv('DATABASE_URL'):
            import sys
            sys.stdout.write(f'[DB CONFIG] Configurado manualmente - HOST: {db_host}, PORT: {db_port}, NAME: {db_name}\n')
            sys.stdout.flush()
# Prioridad 3: Fallback a variables individuales
else:
    # Verificar si estamos en Render o si las variables individuales están disponibles
    db_host = os.getenv('DB_HOST')
    db_name = os.getenv('DB_NAME')
    db_user = os.getenv('DB_USER')
    db_password = os.getenv('DB_PASSWORD')
    db_port = os.getenv('DB_PORT')
    
    # Si estamos en Render o las variables están disponibles, usarlas
    is_render = os.getenv('RENDER') is not None
    has_db_vars = all([db_host, db_name, db_user, db_password])
    
    if is_render or os.getenv('DATABASE_URL') or has_db_vars:
        import sys
        sys.stdout.write('[DB CONFIG] Usando fallback a variables individuales\n')
        sys.stdout.write(f'[DB CONFIG] is_render: {is_render}, has_db_vars: {has_db_vars}\n')
        sys.stdout.write(f'[DB CONFIG] DB_HOST: {db_host or "NO CONFIGURADO"}\n')
        sys.stdout.write(f'[DB CONFIG] DB_NAME: {db_name or "NO CONFIGURADO"}\n')
        sys.stdout.write(f'[DB CONFIG] DB_USER: {db_user or "NO CONFIGURADO"}\n')
        sys.stdout.write(f'[DB CONFIG] DB_PORT: {db_port or "NO CONFIGURADO"}\n')
        sys.stdout.flush()
    
    # Usar las variables si están disponibles, de lo contrario usar valores por defecto
    DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME': db_name or 'postgres',
            'USER': db_user or 'postgres',
            'PASSWORD': db_password or 'postgres',
            'HOST': db_host or 'localhost',
            'PORT': db_port or '5432',
            'OPTIONS': {
                'client_encoding': 'utf8'
            }
        }
    }
    
    if is_render or os.getenv('DATABASE_URL') or has_db_vars:
        import sys
        sys.stdout.write(f'[DB CONFIG] Configuración final - HOST: {DATABASES["default"]["HOST"]}, PORT: {DATABASES["default"]["PORT"]}, NAME: {DATABASES["default"]["NAME"]}\n')
        sys.stdout.flush()


DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL= "loginApp.Usuario"

LOGIN_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'loginApp/static'),)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files finders para theming por tenant
STATICFILES_FINDERS = [
    'globalAdmin.static_loaders.TenantStaticFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Tema por defecto del tenant (se actualiza dinámicamente por el middleware)
CURRENT_TENANT_THEME = 'default'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TENANT_MODEL = 'clientManager.Empresa'

TENANT_DOMAIN_MODEL = 'clientManager.Dominio'

# Configuración para forzar schema público en ciertas URLs
# Las URLs que empiezan con /global/ siempre se procesan en el schema público
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

# URLs que deben procesarse en el schema público (sin identificar tenant)
# Cuando no se identifica un tenant, usar estas URLs
PUBLIC_SCHEMA_URLCONF = 'globalAdmin.urls_public'

# ========== CONFIGURACIÓN DE REST FRAMEWORK PARA API MÓVIL ==========

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api_mobile.authentication.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# Configuración de JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id_usuario',
    'USER_ID_CLAIM': 'user_id',
}

# ========== CONFIGURACIÓN DE CORS PARA API MÓVIL ==========

CORS_ALLOWED_ORIGINS = [
    "http://localhost:19000",  # Expo web
    "http://localhost:19006",  # Expo alternativo
    "http://127.0.0.1:19000",
    "http://127.0.0.1:19006",
    "exp://192.168.100.25:19000",  # Expo en tu red local
    "exp://localhost:19000",
]

# Permitir todas las solicitudes desde la app móvil en desarrollo
# En producción, configurar CORS_ALLOWED_ORIGINS desde variables de entorno
cors_allowed_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_allowed_origins_env:
    CORS_ALLOWED_ORIGINS = cors_allowed_origins_env.split(',')
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = True  # Solo en desarrollo

# Permitir headers personalizados para la API móvil
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-schema',  # Header personalizado para identificar el tenant
    'X-Tenant-Schema',  # También en mayúsculas
]  # Solo para desarrollo, cambiar en producción

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ========== CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN ==========
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True